### PR TITLE
Fix typo from #22

### PR DESCRIPTION
**Pull request by mak**

### CODE REVIEW

**Comment by spender-sandbox** [comment]
This is the wrong fix -- the BOOL is_bytes_in_buf(PCHAR buf, ULONG len, PCHAR memstr, ULONG memlen, ULONG maxsearchbytes) in misc.c should be changed to is_bytes_in_buffer since that's what's used everywhere else.

-Brad

**Comment by KillerInstinct** [comment]
This typo was already fixed in the PR: https://github.com/spender-sandbox/cuckoomon-modified/commit/7aa422647c91e1e841292c3b4b7b3799fdda4ad4

and I used 'buf' due to the replace_-type-_in_buf functions directly below it.

**Comment by spender-sandbox** [comment]
Aha, in that case, nevermind -- my mistake for trusting github :)

-Brad

**Comment by KillerInstinct** [comment]
Yeah nevermind my comment. The 'typo' fix I applied was manually via github's web inf and not the git client. Forgot the .h :) Thanks for the catch.

**Pull request merged**
